version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    restart: unless-stopped
    command:
      # Set loglevel
      - --log.level=DEBUG
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      # Enable dashboard
      - --api.dashboard=true

        # Configure entrypoint
      # HTTP/S protocols
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Global HTTP -> HTTPS
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # Set up LetsEncrypt
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      # Set up the TLS configuration for our websecure listener (basically gives wildcard cert for the main domain)
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=le
      - --entrypoints.websecure.http.tls.domains[0].main=${MAIN_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${MAIN_DOMAIN}

      - --entrypoints.websecure.http.tls.domains[1].main=basketwhisperer.com
      - --entrypoints.websecure.http.tls.domains[1].sans=*.basketwhisperer.com
      - --entrypoints.websecure.http.tls.domains[2].main=chatgptbeat.com
      - --entrypoints.websecure.http.tls.domains[2].sans=*.chatgptbeat.com

      # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.web.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22

    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      # To persist certificates
      - /var/lib/docker/volumes/traefik/_data/letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dash.rule=Host(`${MANAGE_DOMAIN}`)"
      - "traefik.http.routers.traefik-dash.entrypoints=websecure"
      - "traefik.http.routers.traefik-dash.service=api@internal"
      - "traefik.http.routers.traefik-dash.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_USERNAME}:${BASIC_AUTH_PASSWORD_HASH}"

networks:
  proxy:
    external: true
